### PR TITLE
fix(MinterGateway): add maxUpdateCollateralPerInterval

### PR DESCRIPTION
**Pull request by PierrickGT**

### CODE REVIEW

**Review by deluca-mike — COMMENTED** [review]
I think a simpler solution is just simply to prevent an update in `_updateCollateral` if `minTimestamp <= lastUpdateTimestamp + updateInterval()/maxUpdatesPerInterval()`, which would simply be to slightly change the already existing if statement.

**Comment by PierrickGT** [comment]
> I think a simpler solution is just simply to prevent an update in `_updateCollateral` if `minTimestamp <= lastUpdateTimestamp + updateInterval()/maxUpdatesPerInterval()`, which would simply be to slightly change the already existing if statement.
> 
> We don't need to explicitly limit a certain number of updates per interval, we just need to give the effect of it.

Let's say `maxUpdatesPerInterval()` is `4` and `updateInterval()` is 24 hours. 
It would revert if trying to update before `24 / 4 = 6` hours has passed between the past update timestamp and the current one?

**Review by toninorair — CHANGES_REQUESTED** [review]
It can be simplified by adding check 

```if(block.timestamp - lastUpdateTimestamp < UPDATE_COLLATERAL_INTERVAL / UPDATE_COLLATERAL_INTERVAL_MAX_FREQUENCT) revert SomeValidErrorMessage()```

**Comment by PierrickGT** [comment]
Closed in favor of https://github.com/MZero-Labs/protocol/pull/170

**Pull request closed without merging**
